version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_app
    volumes:
      - .:/app
    command: ["pytest", "test/", "--asyncio-mode=auto", "--disable-warnings", "-v"]
    environment:
      - DATABASE_URL=sqlite:///./test_db.db
    depends_on:
      - pre-commit
    ports:
      - "8000:8000"

  pre-commit:
    image: python:3.11-slim
    container_name: pre_commit
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["pre-commit", "run", "--all-files"]
