version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test_db.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/test
    ports:
      - "8080:8080"

volumes:
  db_data:
